AllCops:
  Exclude:
    - 'serverspec-aws.gemspec'

Style/Encoding:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/FileName:
  Enabled: true
  Exclude: ['lib/serverspec-aws.rb']

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 80

Metrics/BlockLength:
  Max: 50
  ExcludedMethods: RSpec.describe
