# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: serverspec-aws 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "serverspec-aws"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["\u{218}tefan", "Rusu"]
  s.date = "2015-07-01"
  s.description = "Serverspec resources for testing the AWS infrastructure"
  s.email = "saltwaterc@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    "lib/resources/common.rb",
    "lib/serverspec-aws.rb"
  ]
  s.homepage = "https://github.com/SaltwaterC/serverspec-aws"
  s.licenses = ["BSD 3-Clause"]
  s.rubygems_version = "2.4.5"
  s.summary = "Serverspec for AWS"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 2"])
      s.add_runtime_dependency(%q<serverspec>, ["~> 2"])
      s.add_runtime_dependency(%q<require_all>, ["~> 1"])
      s.add_runtime_dependency(%q<rubocop>, ["~> 0.31"])
      s.add_runtime_dependency(%q<rspec>, ["~> 3"])
      s.add_runtime_dependency(%q<yard>, ["~> 0.8"])
      s.add_runtime_dependency(%q<guard-rspec>, ["~> 4"])
      s.add_runtime_dependency(%q<guard-rubocop>, ["~> 1"])
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 2"])
      s.add_runtime_dependency(%q<serverspec>, ["~> 2"])
      s.add_runtime_dependency(%q<require_all>, ["~> 1"])
      s.add_development_dependency(%q<rubocop>, ["~> 0.31"])
      s.add_development_dependency(%q<rspec>, ["~> 3"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 4"])
      s.add_development_dependency(%q<guard-rubocop>, ["~> 1"])
    else
      s.add_dependency(%q<aws-sdk>, ["~> 2"])
      s.add_dependency(%q<serverspec>, ["~> 2"])
      s.add_dependency(%q<require_all>, ["~> 1"])
      s.add_dependency(%q<rubocop>, ["~> 0.31"])
      s.add_dependency(%q<rspec>, ["~> 3"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<guard-rspec>, ["~> 4"])
      s.add_dependency(%q<guard-rubocop>, ["~> 1"])
      s.add_dependency(%q<aws-sdk>, ["~> 2"])
      s.add_dependency(%q<serverspec>, ["~> 2"])
      s.add_dependency(%q<require_all>, ["~> 1"])
      s.add_dependency(%q<rubocop>, ["~> 0.31"])
      s.add_dependency(%q<rspec>, ["~> 3"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<guard-rspec>, ["~> 4"])
      s.add_dependency(%q<guard-rubocop>, ["~> 1"])
    end
  else
    s.add_dependency(%q<aws-sdk>, ["~> 2"])
    s.add_dependency(%q<serverspec>, ["~> 2"])
    s.add_dependency(%q<require_all>, ["~> 1"])
    s.add_dependency(%q<rubocop>, ["~> 0.31"])
    s.add_dependency(%q<rspec>, ["~> 3"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<guard-rspec>, ["~> 4"])
    s.add_dependency(%q<guard-rubocop>, ["~> 1"])
    s.add_dependency(%q<aws-sdk>, ["~> 2"])
    s.add_dependency(%q<serverspec>, ["~> 2"])
    s.add_dependency(%q<require_all>, ["~> 1"])
    s.add_dependency(%q<rubocop>, ["~> 0.31"])
    s.add_dependency(%q<rspec>, ["~> 3"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<guard-rspec>, ["~> 4"])
    s.add_dependency(%q<guard-rubocop>, ["~> 1"])
  end
end

